/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as RecordIndexImport } from './routes/record/index'
import { Route as RecordRecordIdImport } from './routes/record/$recordId'
import { Route as MemorizeMemorizeIdImport } from './routes/memorize/$memorizeId'
import { Route as MemorizeMemorizeIdRecordImport } from './routes/memorize/$memorizeId/record'
import { Route as MemorizeMemorizeIdMainTextImport } from './routes/memorize/$memorizeId/main-text'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecordIndexRoute = RecordIndexImport.update({
  path: '/record/',
  getParentRoute: () => rootRoute,
} as any)

const RecordRecordIdRoute = RecordRecordIdImport.update({
  path: '/record/$recordId',
  getParentRoute: () => rootRoute,
} as any)

const MemorizeMemorizeIdRoute = MemorizeMemorizeIdImport.update({
  path: '/memorize/$memorizeId',
  getParentRoute: () => rootRoute,
} as any)

const MemorizeMemorizeIdRecordRoute = MemorizeMemorizeIdRecordImport.update({
  path: '/record',
  getParentRoute: () => MemorizeMemorizeIdRoute,
} as any)

const MemorizeMemorizeIdMainTextRoute = MemorizeMemorizeIdMainTextImport.update(
  {
    path: '/main-text',
    getParentRoute: () => MemorizeMemorizeIdRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/memorize/$memorizeId': {
      id: '/memorize/$memorizeId'
      path: '/memorize/$memorizeId'
      fullPath: '/memorize/$memorizeId'
      preLoaderRoute: typeof MemorizeMemorizeIdImport
      parentRoute: typeof rootRoute
    }
    '/record/$recordId': {
      id: '/record/$recordId'
      path: '/record/$recordId'
      fullPath: '/record/$recordId'
      preLoaderRoute: typeof RecordRecordIdImport
      parentRoute: typeof rootRoute
    }
    '/record/': {
      id: '/record/'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordIndexImport
      parentRoute: typeof rootRoute
    }
    '/memorize/$memorizeId/main-text': {
      id: '/memorize/$memorizeId/main-text'
      path: '/main-text'
      fullPath: '/memorize/$memorizeId/main-text'
      preLoaderRoute: typeof MemorizeMemorizeIdMainTextImport
      parentRoute: typeof MemorizeMemorizeIdImport
    }
    '/memorize/$memorizeId/record': {
      id: '/memorize/$memorizeId/record'
      path: '/record'
      fullPath: '/memorize/$memorizeId/record'
      preLoaderRoute: typeof MemorizeMemorizeIdRecordImport
      parentRoute: typeof MemorizeMemorizeIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutRoute,
  MemorizeMemorizeIdRoute: MemorizeMemorizeIdRoute.addChildren({
    MemorizeMemorizeIdMainTextRoute,
    MemorizeMemorizeIdRecordRoute,
  }),
  RecordRecordIdRoute,
  RecordIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/about",
        "/memorize/$memorizeId",
        "/record/$recordId",
        "/record/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/memorize/$memorizeId": {
      "filePath": "memorize/$memorizeId.tsx",
      "children": [
        "/memorize/$memorizeId/main-text",
        "/memorize/$memorizeId/record"
      ]
    },
    "/record/$recordId": {
      "filePath": "record/$recordId.tsx"
    },
    "/record/": {
      "filePath": "record/index.tsx"
    },
    "/memorize/$memorizeId/main-text": {
      "filePath": "memorize/$memorizeId/main-text.tsx",
      "parent": "/memorize/$memorizeId"
    },
    "/memorize/$memorizeId/record": {
      "filePath": "memorize/$memorizeId/record.tsx",
      "parent": "/memorize/$memorizeId"
    }
  }
}
ROUTE_MANIFEST_END */
