/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as RecordIndexImport } from './routes/record/index'
import { Route as MainTextIndexImport } from './routes/main-text/index'
import { Route as RecordRecordIdImport } from './routes/record/$recordId'
import { Route as MainTextMainTextIdIndexImport } from './routes/main-text/$mainTextId/index'
import { Route as MainTextMainTextIdEditImport } from './routes/main-text/$mainTextId/edit'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecordIndexRoute = RecordIndexImport.update({
  path: '/record/',
  getParentRoute: () => rootRoute,
} as any)

const MainTextIndexRoute = MainTextIndexImport.update({
  path: '/main-text/',
  getParentRoute: () => rootRoute,
} as any)

const RecordRecordIdRoute = RecordRecordIdImport.update({
  path: '/record/$recordId',
  getParentRoute: () => rootRoute,
} as any)

const MainTextMainTextIdIndexRoute = MainTextMainTextIdIndexImport.update({
  path: '/main-text/$mainTextId/',
  getParentRoute: () => rootRoute,
} as any)

const MainTextMainTextIdEditRoute = MainTextMainTextIdEditImport.update({
  path: '/main-text/$mainTextId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/record/$recordId': {
      id: '/record/$recordId'
      path: '/record/$recordId'
      fullPath: '/record/$recordId'
      preLoaderRoute: typeof RecordRecordIdImport
      parentRoute: typeof rootRoute
    }
    '/main-text/': {
      id: '/main-text/'
      path: '/main-text'
      fullPath: '/main-text'
      preLoaderRoute: typeof MainTextIndexImport
      parentRoute: typeof rootRoute
    }
    '/record/': {
      id: '/record/'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordIndexImport
      parentRoute: typeof rootRoute
    }
    '/main-text/$mainTextId/edit': {
      id: '/main-text/$mainTextId/edit'
      path: '/main-text/$mainTextId/edit'
      fullPath: '/main-text/$mainTextId/edit'
      preLoaderRoute: typeof MainTextMainTextIdEditImport
      parentRoute: typeof rootRoute
    }
    '/main-text/$mainTextId/': {
      id: '/main-text/$mainTextId/'
      path: '/main-text/$mainTextId'
      fullPath: '/main-text/$mainTextId'
      preLoaderRoute: typeof MainTextMainTextIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutRoute,
  RecordRecordIdRoute,
  MainTextIndexRoute,
  RecordIndexRoute,
  MainTextMainTextIdEditRoute,
  MainTextMainTextIdIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/about",
        "/record/$recordId",
        "/main-text/",
        "/record/",
        "/main-text/$mainTextId/edit",
        "/main-text/$mainTextId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/record/$recordId": {
      "filePath": "record/$recordId.tsx"
    },
    "/main-text/": {
      "filePath": "main-text/index.tsx"
    },
    "/record/": {
      "filePath": "record/index.tsx"
    },
    "/main-text/$mainTextId/edit": {
      "filePath": "main-text/$mainTextId/edit.tsx"
    },
    "/main-text/$mainTextId/": {
      "filePath": "main-text/$mainTextId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
